server:
  port: 9333
spring:
  application:
    name: SEARCH-SERVICE
  cloud:
    gateway:
      discovery:
        enabled: true
        locator:
          lower-case-service-id: true
          enabled: true
  profiles:
    active: search
elasticsearch:
  host: localhost
  port: 9200
  url: localhost:9200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
    hostname: localhost
log:
  app-name: search
restClient:
  productInfoUrl: http://localhost:8081/api/products
  metricsUrl: http://localhost:9999/api/products
# elastic query parameters
## for menu-tree-finder-v3 index
products-index-name: products-reindex-2
products-index-highlighted-fields: name.ngrams
