server:
  port: 8081
spring:
  application:
    name: read
  zipkin:
    base-url: http://localhost:9411
  logging:
    logstash:
      enabled: true
      url: 192.168.99.100:5000
      ignorePatterns: /(actuator|swagger|webjars).*

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false