server:
  port: 8081
spring:
  application:
    name: READ-SERVICE
  cloud:
    gateway:
      discovery:
        enabled: true
        locator:
          lower-case-service-id: true
          enabled: true
  profiles:
    active: read
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
    hostname: localhost

log:
  app-name: read